name: Deploy to GitHub Pages

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main  # This will trigger the workflow when you push to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # This checks out your repo

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # This uploads the artifact
        with:
          name: github-pages  # This is the name of the artifact
          path: .  # Path to all files in your repo (or specify a folder like 'dist' if needed)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4  # This deploys to GitHub Pages
        with:
          artifact_name: github-pages  # This matches the name used in the upload step
